import { useState } from "react"
import { Info, X } from "lucide-react"
import { Button } from "@/components/ui/button"

/**
 * InfoButton displays an icon button that opens a modal with information.
 */
export function InfoButton() {
    const [isOpen, setIsOpen] = useState(false)

    return (
        <>
            <Button
                variant="outline"
                className="bg-background border border-gray text-gray-600 dark:text-gray-200 h-10 flex items-center justify-center p-2"
                onClick={() => setIsOpen(true)}
            >
                <Info className="h-[1.2rem] w-[1.2rem]" />
                <span className="sr-only">Info</span>
            </Button>

            {isOpen && (
                <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 z-50">
                    <div className="bg-background dark:bg-gray-800 p-6 rounded-lg relative max-w-md w-full shadow-lg">
                        <button
                            className="absolute top-3 right-3"
                            onClick={() => setIsOpen(false)}
                            aria-label="Close"
                        >
                            <X className="h-5 w-5 text-gray-600 dark:text-gray-200" />
                        </button>

                        <h2 className="text-lg font-semibold mb-2 text-gray-800 dark:text-gray-100">
                            Information
                        </h2>
                        <p className="text-gray-700 dark:text-gray-300">
                            <br></br>


                            <p>
                                The content and responses generated by this digital assistant are derived solely from the department’s official study guide and are provided for informational purposes only. While every effort has been made to ensure accuracy, errors or omissions may occur. Users are advised to independently verify all information before relying upon it.
                            </p>
                            <br></br>
                            <h3>Software Attribution:</h3>
                            <ul>
                                <li>
                                    <br></br>
                                    <strong>Frontend:</strong> The graphical user interface was originally developed by Leon Binder and Christoph Handschuh and subsequently adapted to fulfill the requirements of the diploma thesis.
                                </li>
                                <li>
                                    <br></br>
                                    <strong>Backend:</strong> The core processing engine, including advanced data‑preprocessing techniques and a Retrieval‑Augmented Generation (RAG) pipeline, was designed and implemented exclusively by Christos Kiokakis as part of his undergraduate thesis.
                                </li>
                            </ul>
                            <br></br>
                            <p>
                                For inquiries or permissions beyond the scope of this notice, please contact{' '}
                                <a
                                    href="https://www.linkedin.com/in/christos-kiokakis-3573a014a/"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    <i>Christos Kiokakis</i>
                                </a>.
                            </p>
                            <br></br><br></br>
                            <p><strong>© 2025 Christos Kiokakis. All rights reserved.</strong></p>
                        </p>
                    </div>
                </div>
            )}
        </>
    )
}
