import { useState } from "react";
import { Info, X } from "lucide-react";
import { Button } from "@/components/ui/button";

/**
 * InfoButton displays an icon button that opens a modal with information.
 */
export function InfoButton() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      <Button
        variant="outline"
        className="bg-background border border-gray text-gray-600 dark:text-gray-200 h-10 flex items-center justify-center p-2"
        onClick={() => setIsOpen(true)}
      >
        <Info className="h-[1.2rem] w-[1.2rem]" />
        <span className="sr-only">Info</span>
      </Button>

      {isOpen && (
        <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 z-50 px-4">
          <div className="relative bg-background dark:bg-gray-800 rounded-lg shadow-lg w-full max-w-2xl max-h-[90vh] overflow-y-auto p-6 sm:p-8">
            <button
              className="absolute top-3 right-3"
              onClick={() => setIsOpen(false)}
              aria-label="Close"
            >
              <X className="h-5 w-5 text-gray-600 dark:text-gray-200" />
            </button>

            <h2 className="text-lg font-semibold mb-4 text-gray-800 dark:text-gray-100">
              Information
            </h2>

            <div className="space-y-4 text-sm text-gray-700 dark:text-gray-300">
              <p>
                The content and responses generated by this digital assistant are derived solely from the department’s official study guide and are provided for informational purposes only. While every effort has been made to ensure accuracy, errors or omissions may occur. Users are advised to independently verify all information before relying upon it.
              </p>

              <div>
                <h3 className="font-semibold">Software Attribution:</h3>
                <ul className="list-disc list-inside pl-2 space-y-2">
                  <li>
                    <strong>Frontend:</strong> The graphical user interface was originally developed by Leon Binder and Christoph Handschuh and subsequently adapted to fulfill the requirements of the diploma thesis.
                  </li>
                  <li>
                    <strong>Backend:</strong> The core processing engine, including advanced data‑preprocessing techniques and a Retrieval‑Augmented Generation (RAG) pipeline, was designed and implemented exclusively by Christos Kiokakis as part of his undergraduate thesis.
                  </li>
                </ul>
              </div>

              <p>
                For inquiries or permissions beyond the scope of this notice, please contact{" "}
                <a
                  href="https://www.linkedin.com/in/christos-kiokakis-3573a014a/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline hover:text-primary"
                >
                  <i>Christos Kiokakis</i>
                </a>.
              </p>

              <p className="font-semibold">© 2025 Christos Kiokakis. All rights reserved.</p>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
